#!/bin/sh
set -e
# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask hv-fcopy-daemon.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled hv-fcopy-daemon.service; then
        # Enables the unit on first installation, creates new
        # symlinks on upgrades if the unit file has changed.
        deb-systemd-helper enable hv-fcopy-daemon.service >/dev/null || true
else
        # Update the statefile to add new symlinks (if any), which need to be
        # cleaned up on purge. Also remove old symlinks.
        deb-systemd-helper update-state hv-fcopy-daemon.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask hv-kvp-daemon.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled hv-kvp-daemon.service; then
        # Enables the unit on first installation, creates new
        # symlinks on upgrades if the unit file has changed.
        deb-systemd-helper enable hv-kvp-daemon.service >/dev/null || true
else
        # Update the statefile to add new symlinks (if any), which need to be
        # cleaned up on purge. Also remove old symlinks.
        deb-systemd-helper update-state hv-kvp-daemon.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask hv-vss-daemon.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled hv-vss-daemon.service; then
        # Enables the unit on first installation, creates new
        # symlinks on upgrades if the unit file has changed.
        deb-systemd-helper enable hv-vss-daemon.service >/dev/null || true
else
        # Update the statefile to add new symlinks (if any), which need to be
        # cleaned up on purge. Also remove old symlinks.
        deb-systemd-helper update-state hv-vss-daemon.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
        if [ -x "/etc/init.d/hv-kvp-daemon" ]; then
                update-rc.d hv-kvp-daemon defaults >/dev/null
        fi
        if [ -x "/etc/init.d/hv-kvp-daemon" ] || [ -e "/etc/init/hv-kvp-daemon.conf" ]; then
                invoke-rc.d hv-kvp-daemon start || exit $?
        fi
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
        if [ -x "/etc/init.d/hv-vss-daemon" ]; then
                update-rc.d hv-vss-daemon defaults >/dev/null
        fi
        if [ -x "/etc/init.d/hv-vss-daemon" ] || [ -e "/etc/init/hv-vss-daemon.conf" ]; then
                invoke-rc.d hv-vss-daemon start || exit $?
        fi
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
        if [ -x "/etc/init.d/hv-fcopy-daemon" ]; then
                update-rc.d hv-fcopy-daemon defaults >/dev/null
        fi
        if [ -x "/etc/init.d/hv-fcopy-daemon" ] || [ -e "/etc/init/hv-fcopy-daemon.conf" ]; then
                invoke-rc.d hv-fcopy-daemon start || exit $?
        fi
fi
# End automatically added section
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
        deb-systemd-invoke start hv-fcopy-daemon.service hv-kvp-daemon.service hv-vss-daemon.service > /dev/null 2>&1 || true
fi
# End automatically added section
