#!/bin/sh
set -e
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper mask hv-fcopy-daemon.service hv-kvp-daemon.service hv-vss-daemon.service >/dev/null
        fi
        if [[ -e /etc/systemd/system/hv-kvp-daemon.service ]];then
                rm -f /etc/systemd/system/hv-kvp-daemon.service
        fi
        if [[ -e /etc/systemd/system/hv-vss-daemon.service ]];then
                rm -f /etc/systemd/system/hv-vss-daemon.service
        fi
        if [[ -e /etc/systemd/system/hv-fcopy-daemon.service ]];then
                rm -f /etc/systemd/system/hv-fcopy-daemon.service
        fi
fi

if [ "$1" = "purge" ]; then
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper purge hv-fcopy-daemon.service hv-kvp-daemon.service hv-vss-daemon.service >/dev/null
                deb-systemd-helper unmask hv-fcopy-daemon.service hv-kvp-daemon.service hv-vss-daemon.service >/dev/null
        fi
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
        update-rc.d hv-kvp-daemon remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
        systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
        update-rc.d hv-vss-daemon remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
        systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
        update-rc.d hv-fcopy-daemon remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
        systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
