#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/hv-kvp-daemon" ] || [ -e "/etc/init/hv-kvp-daemon.conf" ]; then
	if [ ! -e "/etc/init/hv-kvp-daemon.conf" ]; then
		update-rc.d hv-kvp-daemon defaults >/dev/null
	fi
	invoke-rc.d hv-kvp-daemon start || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f hv-kvp-daemon remove >/dev/null || exit $?
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/hv-vss-daemon" ] || [ -e "/etc/init/hv-vss-daemon.conf" ]; then
	if [ ! -e "/etc/init/hv-vss-daemon.conf" ]; then
		update-rc.d hv-vss-daemon defaults >/dev/null
	fi
	invoke-rc.d hv-vss-daemon start || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f hv-vss-daemon remove >/dev/null || exit $?
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/hv-fcopy-daemon" ] || [ -e "/etc/init/hv-fcopy-daemon.conf" ]; then
	if [ ! -e "/etc/init/hv-fcopy-daemon.conf" ]; then
		update-rc.d hv-fcopy-daemon defaults >/dev/null
	fi
	invoke-rc.d hv-fcopy-daemon start || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f hv-fcopy-daemon remove >/dev/null || exit $?
# End automatically added section
