#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/hv-kvp-daemon" ] && [ -L "/etc/init.d/hv-kvp-daemon" ] \
	   && [ $(readlink -f "/etc/init.d/hv-kvp-daemon") = /lib/init/upstart-job ]
	then
		rm -f "/etc/init.d/hv-kvp-daemon"
	fi
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/hv-vss-daemon" ] && [ -L "/etc/init.d/hv-vss-daemon" ] \
	   && [ $(readlink -f "/etc/init.d/hv-vss-daemon") = /lib/init/upstart-job ]
	then
		rm -f "/etc/init.d/hv-vss-daemon"
	fi
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/hv-fcopy-daemon" ] && [ -L "/etc/init.d/hv-fcopy-daemon" ] \
	   && [ $(readlink -f "/etc/init.d/hv-fcopy-daemon") = /lib/init/upstart-job ]
	then
		rm -f "/etc/init.d/hv-fcopy-daemon"
	fi
fi
# End automatically added section
