#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/hv-kvp-daemon" ] || [ -e "/etc/init/hv-kvp-daemon.conf" ]; then
	invoke-rc.d hv-kvp-daemon stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/hv-vss-daemon" ] || [ -e "/etc/init/hv-vss-daemon.conf" ]; then
	invoke-rc.d hv-vss-daemon stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/hv-fcopy-daemon" ] || [ -e "/etc/init/hv-fcopy-daemon.conf" ]; then
	invoke-rc.d hv-fcopy-daemon stop || exit $?
fi
# End automatically added section
